#!/usr/bin/env php
<?php
/**
 * silex-chisel
 * 
 * @author  Filipe Dobreira <https://github.com/filp>
 * @license MIT
 */

$app = require __DIR__ . "/bootstrap.php";

use Chisel\Console\ChiselApplication;
use Chisel\Console\Command\GeneratorCommand;

$chisel = new ChiselApplication($app);
$chisel->addFromDirectory($app["path.commands"]);
$chisel->add(new GeneratorCommand);
$chisel->run();