#!/usr/bin/env php
<?php
/**
 * silex-chisel
 * 
 * @author  Filipe Dobreira <https://github.com/filp>
 * @license MIT
 */
require __DIR__ . "/../vendor/autoload.php";

use Chisel\Console\ChiselApplication;
use Chisel\Console\Command\GeneratorCommand;
use Silex\Application;

$app    = new Silex\Application;
$chisel = new ChiselApplication($app);
$chisel->addFromDirectory(__DIR__ . "/commands");
$chisel->add(new GeneratorCommand);
$chisel->run();